### ISSUE TITLE
Make GitoliteAdmin#rm_key Require an Instance of Gitolite::SSHKey

### ISSUE THREAD

**Issue by RLovelett** [wingrunr21/gitolite#13]
Similar to how GitoliteAdmin#add_key is already implemented require GitoliteAdmin#rm_key require an Instance of Gitolite::SSHKey.

I'll be issuing a pull request on this later.

**Comment by wingrunr21** [comment]
Already implemented that. Going to issue a new version later today.

**Comment by RLovelett** [comment]
Awesome, thanks!

**Comment by wingrunr21** [comment]
Resolved in 0b05fffb4f
