### ISSUE TITLE
Wildcard Repo Support

### ISSUE THREAD

**Issue by RLovelett** [wingrunr21/gitolite#15]
Currently if you have a wildcard repo in your gitolite.conf file you will get an error like this when loading that admin repo: `C is not in the allowed list of permissions!`

Technically, `C` is valid. I am not sure that full wildcard repo support is required but if it could at the least recognize the permissions so the rest of the repo will load that would be great.

http://sitaramc.github.com/gitolite/conf.html#gitolite_conf_summary_permissions_

**Comment by wingrunr21** [comment]
Do you have wildcard repos enabled in your gitolite config?

http://sitaramc.github.com/gitolite/rc.html

Also, the regex gitolite itself uses is used to check valid perms.  Let me look into this.

**Comment by RLovelett** [comment]
Yeah, everything from the Gitolite side of things works just fine. I can create, commit, push and pull from the wildcard repos.

I just have the issue when loading the configuration with this gem.

**Comment by wingrunr21** [comment]
I see the issue in the regex.  Let me write a test and push a fix up to github.  Give me about 15.

**Comment by RLovelett** [comment]
Sounds great! Thanks for the quick turn around on this.

**Comment by wingrunr21** [comment]
Fixed in cb100415e7
