### ISSUE TITLE
Rails 3.2

### ISSUE THREAD

**Issue by dzaporozhets** [wingrunr21/gitolite#19]
This issue related to one of dependencies gem.  Feel free to close it. 

But this is a reason why i cant use your gem v1.x  for GITLAB. 

You have a `plexus` gem dependency.  Which depends on `facets`.  https://github.com/rubyworks/facets/issues/55

So after update to `gitolite v1.0` i cant start my application. Sorry if I am wrong & missed something

**Comment by wingrunr21** [comment]
Ok I will look into it.

**Comment by dzaporozhets** [comment]
Maybe fixed https://github.com/rubyworks/facets/issues/55#issuecomment-5958650

**Comment by wingrunr21** [comment]
Ok, it looks like the solution, for the time being, is probably going to be putting <tt>facets</tt> before <tt>gitolite</tt>in the Gemfile

```
gem 'facets', :git => 'git://github.com/rubyworks/facets.git'
gem 'gitolite'
```

<tt>plexus</tt> does not depend on a specific version of facets so I believe that will fix the issue.  You could fork <tt>facets</tt> or lock the Gemfile to a specific SHA if you are worried about things breaking via installing <tt>facets</tt> from git.

**Comment by wingrunr21** [comment]
<tt>facets</tt> appears to be compatible now.  <tt>plexus</tt>, however, is not.

<tt>plexus</tt> [Issue #2](https://github.com/chikamichi/plexus/issues/2) deals with the issue

**Comment by dzaporozhets** [comment]
So i still wont be able to use it, right?

**Comment by wingrunr21** [comment]
It looks like the issue with <tt>plexus</tt> has not been looked at.  I will take a look tonight and either see if I can fix the problem or look into a different graph library (<tt>gratr19</tt> may be an option).

**Comment by wingrunr21** [comment]
I found the <tt>plexus</tt> issue.  I have fixed it but, due to their test suite not passing, can't tell if I further broke things or if things are the same.

**Comment by julionc** [comment]
This has been working great but today I updated Rails to 3.2.8 which the stopped one app from working instead returning an actionpack error. ¿?

Anyway, I've solved it (apparently)

```
gem 'gitolite', :github => 'wingrunr21/gitolite', :require => false
```

**Comment by wingrunr21** [comment]
That actually doesn't solve the issue, it just prevents the gem from being required.  Once the gem gets required into Rails you'll see issues.

**Comment by wingrunr21** [comment]
version 1.1.0 fixes this issue by switching from using <tt>plexus</tt> to the <tt>gratr19</tt> library.

**Comment by dzaporozhets** [comment]
@wingrunr21 so i can finally your gem instead of our fork for gitlab? :)

**Comment by wingrunr21** [comment]
Hopefully
