### ISSUE TITLE
Creating new ssh key does not include it into authorized_keys

### ISSUE THREAD

**Issue by albertoleal** [wingrunr21/gitolite#29]
I can add a new key but it's not getting included in ~/.ssh/authorized_keys file. Do you have any clue what the issue could be?

I can see that the ssh-key in under the folder ~/.gitolite/keydir/
<code>
ga_repo.save
 => {"mochila"=>[ssh-rsa AAAAB3NzDaC1yc2EAAAADAQABAAABAQDAzmnImoMaoqh04sCfq2gFkiCZYk1lSrEEwjDtvTrpbp52MGN+NNjpMgsdJndQoWKQnsQ2fVAUXeptHfeAWC1YDcJG+DS+5sQd1PJiCNidk2YQzMHRKpy8bW/hrBanlYzEedjm86eTSKODlWI9CDUAECqdhiE9cqcdBAbMhczheRo64SJSz+TbHd58Tl3ShI8Mo7VHGZ9xZn4JEm3+VAgKlsvlmqBUWKAMOHuffOpy7cCxuuUu1zUE6rh9wIcG5wiuvhFzA+KcyskI74P1XovNIwsKC3YwKTMAlUJAvCiBOOcf2yjFcgztq2OxddGweQwfD2gTUVeYmILGwFzF6gMt mochila]}
ga_repo.apply
 => "" 
</code>

**Comment by wingrunr21** [comment]
This gem does not modify anything except the <tt>gitolite-admin</tt> git repository.  This means that once the changes are made in that repository, you must follow the normal procedures for updating relevant files (ie in this case pushing to master so the <tt>gitolite</tt> backend can update authorized_keys).

See http://sitaramc.github.com/gitolite/admin.html#adminrepo

**Comment by albertoleal** [comment]
That's right. It's related to gitolite backend. What's weird is that the repo has been created, the ssh-key is there, but the authorized_keys file does not get updated. 

thanks.
