### ISSUE TITLE
Drop gitlab-grit and use Rugged

### ISSUE THREAD

**Issue by n-rodriguez** [wingrunr21/gitolite#44]
Hi there!

Why not drop gitlab-grit support and replace it by Rugged https://github.com/libgit2/rugged ?

**Comment by wingrunr21** [comment]
I'm not actively maintaining this gem anymore. If you submit a PR with Rugged supported instead of Grit I'd be open to merging it and cutting a release.

**Comment by n-rodriguez** [comment]
I've looked at it and it seems to be too much work for nothing.
I close this issue.
