### ISSUE TITLE
Ruby 1.8 support

### ISSUE THREAD

**Issue by kubal5003** [wingrunr21/gitolite#9]
Would it be possible to add support for Ruby 1.8 ?

The reason I'm asking is that gitolite is used to develop redmine-gitolite plugin\* for redmine and since redmine still requires ruby 1.8 this is an issue for me. However author of the plugin somehow runs redmine on 1.9 so maybe this is not going to be needed soon..
- \- https://github.com/ivyl/redmine-gitolite

**Comment by wingrunr21** [comment]
I can look into it.  If it is being used in a Rails environment, that means I will not be able to use the ActiveSupport OrderedHash, however.  I'm working on proper thread safety right now but will make this next on the list.  If you know of any good OrderedHash libraries that are not a part of ActiveSupport, that'd help.

Hashery looks promising:
https://github.com/rubyworks/hashery

**Comment by kubal5003** [comment]
I'll try to help as much as I can, but I don't know ruby and rails (I'm a C#/.NET developer). 

PS> Sorry for this "close/reopen" mess, I wrote a comment and it showed "kubal5003 closed the issue just now"

**Comment by kubal5003** [comment]
I've found something that seems to fit: http://loopkid.net/articles/2008/06/19/ordered-hashes-in-ruby-1-8

**Comment by kubal5003** [comment]
I was trying hard today to work on this (I've read ruby tutorial, I know what to do and will figure out how), but I can't figure out how to test the whole thing - gems, gemspec and dependencies is something I wasn't able to grasp in one day.
I'll try to use source files without the whole gem thing, modify them and then hand em over to you.

**Comment by wingrunr21** [comment]
Don't sweat it.  Hashery will work fine for getting Ruby 1.8 support.  I'll implement this later this week.

**Comment by wingrunr21** [comment]
FYI, the only part of the gem that won't work properly in Ruby 1.8 are deny rules.  If you don't have any of those in your config, the gem should work find in 1.8 as-is.  I'll still implement full 1.8 support though.

**Comment by kubal5003** [comment]
Thank you very much. I thought this was going to happen in some not well defined future, but this or even next week sounds great :)
Anyway I've learned something about ruby today so that's not a completely wasted time.

**Comment by wingrunr21** [comment]
Pushed 1.8 support to master today
